### PR TITLE
Unittest for #177 / #192

### PR DESCRIPTION
**Pull request by zsoca8711**
Hello,

this is my first-ever pull request, so please excuse me if i did any mistake or unwanted stuff.

I refactored the code to make sure "createAndFillUserTable" can be used with both bind() and without bind() - may be useful in the future as well.

Please ignore commits b9c6ddd5d8d9876ae245416a3f6eb3cd5bf5f8eb and ad8823e0943b3138e4ccb07cb75bff6d690fe1e3 - the first had some unwanted code pushed, the second is the revert of it.
My last commit (e68c36db8820676b5cc7dc82ecc3b165c307df17) has all the changes i really.

I'm looking forward for any feedback you may have!

### CODE REVIEW

**Comment by aaberg** [comment]
Looks good. Thanks!

Some feedback:
Next time, instead of pushing code that reverses another commit, you can use `git reset` to reset HEAD back to the commit before the commit you wanted to remove. This will make for a cleaner git history. 

Also, I can see that you have fixed some formatting in the code. Next time, put these fixes in it's own commit, as these has nothing to do with the unittest.

**Comment by zsoca8711** [comment]
Hello,

Thanks for git reset, i didn't know it.

On the formatting, i need to be honest, it may have been my IDE, as i didn't do that on purpose. Sorry for that, i'll keep an eye out next time.

**Comment by miere** [comment]
@zsoca8711 nice contribution.

@aaberg @zsoca8711 about code formatting, I have some suggestions (listed bellow). What you guys think about it?
1. Wasn't this a case to use a tool to statically check the code formatting to avoid situations like this. [This question](http://stackoverflow.com/questions/1955514/best-practices-for-code-formatting-on-large-projects) at SO have some interesting suggestions about this subject.
2. Create a CONTRIBUTING.md file and include on it some suggestions about code style. It will make another contributors more comfortable.

Regards

**Comment by aaberg** [comment]
There is already a short document describing the coding guidelines:
https://github.com/aaberg/sql2o/wiki/Coding-guidelines

I like the idea about statically checking the code at compile time, but I don't think it should be necessary. Maybe it is enough to make the coding guidelines more visible? The compile-time code check will anyway just be able to check for things like the use of whitespaces instead of tabs and number of whitespaces etc. It won't be able to check if the contributor has added unwanted code changes.

When using git, it is regardless a best practice to always run a `git status` and a `git diff` before committing changes.

**Pull request merged**
