### PR TITLE
Improvement for executeAndFetchTable().asList()

### PR DESCRIPTION
**Pull request by toni07**
When you use 
`List<Map<String,Object>> ... = con.createQuery(complexSql).executeAndFetchTable().asList()`, you cannot add data in a row of this list. It can sometimes be useful, for example if you have data comming from SQL and you need to merge them with data comming from a file, or other...
Before my change, it was not possible, as the `Map` that represents the SQL row is re-created every time it is accessed.
My change might also make the code faster.

Thanks

### CODE REVIEW

**Comment by zapodot** [comment]
This change will add state to the Row structure which IMHO is not a good idea for various reasons. Both the Row and Table class should be considered to be a view of the data in the database and should thus be immutable

**Comment by toni07** [comment]
Do you think adding a state to Row is a bad idea for design, technical reasons, or philosophical ones? I've been using Hibernate for years now, and the result of a database query is not immutable. Maybe this a bad idea, but in practise you often have to manipulate data after getting it from SQL. Not everything is possible in SQL, and nowadays with APIs, webservices, and so one you often have to merge data coming from different sources. Copying SQL results from an Sql2o structure to a pure Java one is IMHO overkill, both in terms of coding and in terms of processing time.

**Comment by zapodot** [comment]
Adding data to a view opens the API to issues with memory leaks and thread synchronization. I do not challenge the need to manipulate data retrieved from an database or other source, but it should be done by creating new short-lived structures in memory. For instance you can create your own Map instance containing the data from the database and do all sorts on manipulations on them. 

In my experience upholding the immutable principle, especially with libraries and API-s leads gives both a cleaner interface and less trouble.

Note: I am not a maintainer of SQL2O so I have no influence over what is done with this PR

**Comment by toni07** [comment]
Ok, thanks for sharing your thoughts, yes the immutable principle is to be kept as much as possible, but maybe here it could be a good thing to have these objects mutable.
Let's see what happens to my PR...

**Comment by kofrasa** [comment]
I agree with @zapodot. A resultset should be treated as immutable to avoid surprises and also, so it can be shared safely across different areas of the application.

@toni07 perhaps you could wrap the result in your own list and perform the filtering there.

**Pull request closed without merging**
